import type { Metadata } from "next";
import { Roboto, Bebas_Neue } from "next/font/google";
import "./globals.css";




export const roboto = Roboto({
  subsets: ['latin'],
  display: 'swap',
  fallback: ["sans-serif"],
  variable: "--font-roboto",
  weight: ["400", "500", "700"],
})


export const bebas = Bebas_Neue({
  subsets: ["latin"],
  weight: ["400"],
  display: "swap",
  fallback: ["sans-serif"],
  variable: "--font-bebas",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`antialiased ${roboto.className}`}
      >



        {children}


      </body>
    </html>
  );
}
